version: '3.8'


services:
  server:
    build:
      context: .
    environment:
        - NODE_ENV=production  
        - DATABASE_URI=${MONGO_URI} 
        - JWT_SECRET=${JWTS} 
        - PORT=${PORT} 
    ports:
        - 3001:3001
    volumes:
        - .:/app
    command: npm run dev
    depends_on:
        - mongo


  mongo:
    image: mongo:7
    ports:
        - "27017:27017"
    volumes:
        - mongo-data:/data/db
volumes:
  mongo-data:



